<?php
/**
 * ProjectInformationDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.4.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProjectInformationDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectInformationDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectInformationDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectInformationDto"
     */
    public function testProjectInformationDto()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "description_short"
     */
    public function testPropertyDescriptionShort()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "item_number_schema"
     */
    public function testPropertyItemNumberSchema()
    {
    }

    /**
     * Test attribute "currency_short"
     */
    public function testPropertyCurrencyShort()
    {
    }

    /**
     * Test attribute "currency_long"
     */
    public function testPropertyCurrencyLong()
    {
    }

    /**
     * Test attribute "labour_time_label"
     */
    public function testPropertyLabourTimeLabel()
    {
    }

    /**
     * Test attribute "price_components"
     */
    public function testPropertyPriceComponents()
    {
    }
}
