<?php
/**
 * ServiceSpecificationDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AVACloud API 1.4.0
 *
 * AVACloud API specification
 *
 * OpenAPI spec version: 1.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ServiceSpecificationDto Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServiceSpecificationDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ServiceSpecificationDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'project_hourly_wage' => 'float',
        'project_tax_rate' => 'float',
        'project_price_components' => 'string[]',
        'project_item_number_schema' => '\Swagger\Client\Model\ItemNumberSchemaDto',
        'elements' => '\Swagger\Client\Model\IElementDto[]',
        'project_labour_time_label' => 'string',
        'contains_duplicate_item_numbers' => 'bool',
        'ignore_duplicate_item_numbers' => 'bool',
        'total_price_gross_by_tax_rate' => '\Swagger\Client\Model\GrossPriceComponentDto[]',
        'ignore_child_price_updates' => 'bool',
        'deducted_price' => 'float',
        'deduction_factor' => 'float',
        'total_price' => 'float',
        'total_price_gross' => 'float',
        'total_price_gross_deducted' => 'float',
        'price_type' => '\Swagger\Client\Model\PriceTypeDto',
        'bidder' => '\Swagger\Client\Model\PartyInformationDto',
        'gaeb_xml_id' => 'string',
        'project_information' => 'object',
        'exchange_phase' => '\Swagger\Client\Model\ExchangePhaseDto',
        'origin' => '\Swagger\Client\Model\OriginDto',
        'creation_date' => '\DateTime',
        'offer_by_date' => '\DateTime',
        'decision_date' => '\DateTime',
        'submission_location' => 'string',
        'description' => 'string',
        'name' => 'string',
        'price_information' => '\Swagger\Client\Model\PriceInformationDto',
        'project_catalogues' => '\Swagger\Client\Model\CatalogueDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'guid',
        'project_hourly_wage' => 'decimal',
        'project_tax_rate' => 'decimal',
        'project_price_components' => null,
        'project_item_number_schema' => null,
        'elements' => null,
        'project_labour_time_label' => null,
        'contains_duplicate_item_numbers' => null,
        'ignore_duplicate_item_numbers' => null,
        'total_price_gross_by_tax_rate' => null,
        'ignore_child_price_updates' => null,
        'deducted_price' => 'decimal',
        'deduction_factor' => 'decimal',
        'total_price' => 'decimal',
        'total_price_gross' => 'decimal',
        'total_price_gross_deducted' => 'decimal',
        'price_type' => null,
        'bidder' => null,
        'gaeb_xml_id' => null,
        'project_information' => null,
        'exchange_phase' => null,
        'origin' => null,
        'creation_date' => 'date-time',
        'offer_by_date' => 'date-time',
        'decision_date' => 'date-time',
        'submission_location' => null,
        'description' => null,
        'name' => null,
        'price_information' => null,
        'project_catalogues' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'project_hourly_wage' => 'projectHourlyWage',
        'project_tax_rate' => 'projectTaxRate',
        'project_price_components' => 'projectPriceComponents',
        'project_item_number_schema' => 'projectItemNumberSchema',
        'elements' => 'elements',
        'project_labour_time_label' => 'projectLabourTimeLabel',
        'contains_duplicate_item_numbers' => 'containsDuplicateItemNumbers',
        'ignore_duplicate_item_numbers' => 'ignoreDuplicateItemNumbers',
        'total_price_gross_by_tax_rate' => 'totalPriceGrossByTaxRate',
        'ignore_child_price_updates' => 'ignoreChildPriceUpdates',
        'deducted_price' => 'deductedPrice',
        'deduction_factor' => 'deductionFactor',
        'total_price' => 'totalPrice',
        'total_price_gross' => 'totalPriceGross',
        'total_price_gross_deducted' => 'totalPriceGrossDeducted',
        'price_type' => 'priceType',
        'bidder' => 'bidder',
        'gaeb_xml_id' => 'gaebXmlId',
        'project_information' => 'projectInformation',
        'exchange_phase' => 'exchangePhase',
        'origin' => 'origin',
        'creation_date' => 'creationDate',
        'offer_by_date' => 'offerByDate',
        'decision_date' => 'decisionDate',
        'submission_location' => 'submissionLocation',
        'description' => 'description',
        'name' => 'name',
        'price_information' => 'priceInformation',
        'project_catalogues' => 'projectCatalogues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'project_hourly_wage' => 'setProjectHourlyWage',
        'project_tax_rate' => 'setProjectTaxRate',
        'project_price_components' => 'setProjectPriceComponents',
        'project_item_number_schema' => 'setProjectItemNumberSchema',
        'elements' => 'setElements',
        'project_labour_time_label' => 'setProjectLabourTimeLabel',
        'contains_duplicate_item_numbers' => 'setContainsDuplicateItemNumbers',
        'ignore_duplicate_item_numbers' => 'setIgnoreDuplicateItemNumbers',
        'total_price_gross_by_tax_rate' => 'setTotalPriceGrossByTaxRate',
        'ignore_child_price_updates' => 'setIgnoreChildPriceUpdates',
        'deducted_price' => 'setDeductedPrice',
        'deduction_factor' => 'setDeductionFactor',
        'total_price' => 'setTotalPrice',
        'total_price_gross' => 'setTotalPriceGross',
        'total_price_gross_deducted' => 'setTotalPriceGrossDeducted',
        'price_type' => 'setPriceType',
        'bidder' => 'setBidder',
        'gaeb_xml_id' => 'setGaebXmlId',
        'project_information' => 'setProjectInformation',
        'exchange_phase' => 'setExchangePhase',
        'origin' => 'setOrigin',
        'creation_date' => 'setCreationDate',
        'offer_by_date' => 'setOfferByDate',
        'decision_date' => 'setDecisionDate',
        'submission_location' => 'setSubmissionLocation',
        'description' => 'setDescription',
        'name' => 'setName',
        'price_information' => 'setPriceInformation',
        'project_catalogues' => 'setProjectCatalogues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'project_hourly_wage' => 'getProjectHourlyWage',
        'project_tax_rate' => 'getProjectTaxRate',
        'project_price_components' => 'getProjectPriceComponents',
        'project_item_number_schema' => 'getProjectItemNumberSchema',
        'elements' => 'getElements',
        'project_labour_time_label' => 'getProjectLabourTimeLabel',
        'contains_duplicate_item_numbers' => 'getContainsDuplicateItemNumbers',
        'ignore_duplicate_item_numbers' => 'getIgnoreDuplicateItemNumbers',
        'total_price_gross_by_tax_rate' => 'getTotalPriceGrossByTaxRate',
        'ignore_child_price_updates' => 'getIgnoreChildPriceUpdates',
        'deducted_price' => 'getDeductedPrice',
        'deduction_factor' => 'getDeductionFactor',
        'total_price' => 'getTotalPrice',
        'total_price_gross' => 'getTotalPriceGross',
        'total_price_gross_deducted' => 'getTotalPriceGrossDeducted',
        'price_type' => 'getPriceType',
        'bidder' => 'getBidder',
        'gaeb_xml_id' => 'getGaebXmlId',
        'project_information' => 'getProjectInformation',
        'exchange_phase' => 'getExchangePhase',
        'origin' => 'getOrigin',
        'creation_date' => 'getCreationDate',
        'offer_by_date' => 'getOfferByDate',
        'decision_date' => 'getDecisionDate',
        'submission_location' => 'getSubmissionLocation',
        'description' => 'getDescription',
        'name' => 'getName',
        'price_information' => 'getPriceInformation',
        'project_catalogues' => 'getProjectCatalogues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['project_hourly_wage'] = isset($data['project_hourly_wage']) ? $data['project_hourly_wage'] : null;
        $this->container['project_tax_rate'] = isset($data['project_tax_rate']) ? $data['project_tax_rate'] : null;
        $this->container['project_price_components'] = isset($data['project_price_components']) ? $data['project_price_components'] : null;
        $this->container['project_item_number_schema'] = isset($data['project_item_number_schema']) ? $data['project_item_number_schema'] : null;
        $this->container['elements'] = isset($data['elements']) ? $data['elements'] : null;
        $this->container['project_labour_time_label'] = isset($data['project_labour_time_label']) ? $data['project_labour_time_label'] : null;
        $this->container['contains_duplicate_item_numbers'] = isset($data['contains_duplicate_item_numbers']) ? $data['contains_duplicate_item_numbers'] : null;
        $this->container['ignore_duplicate_item_numbers'] = isset($data['ignore_duplicate_item_numbers']) ? $data['ignore_duplicate_item_numbers'] : null;
        $this->container['total_price_gross_by_tax_rate'] = isset($data['total_price_gross_by_tax_rate']) ? $data['total_price_gross_by_tax_rate'] : null;
        $this->container['ignore_child_price_updates'] = isset($data['ignore_child_price_updates']) ? $data['ignore_child_price_updates'] : null;
        $this->container['deducted_price'] = isset($data['deducted_price']) ? $data['deducted_price'] : null;
        $this->container['deduction_factor'] = isset($data['deduction_factor']) ? $data['deduction_factor'] : null;
        $this->container['total_price'] = isset($data['total_price']) ? $data['total_price'] : null;
        $this->container['total_price_gross'] = isset($data['total_price_gross']) ? $data['total_price_gross'] : null;
        $this->container['total_price_gross_deducted'] = isset($data['total_price_gross_deducted']) ? $data['total_price_gross_deducted'] : null;
        $this->container['price_type'] = isset($data['price_type']) ? $data['price_type'] : null;
        $this->container['bidder'] = isset($data['bidder']) ? $data['bidder'] : null;
        $this->container['gaeb_xml_id'] = isset($data['gaeb_xml_id']) ? $data['gaeb_xml_id'] : null;
        $this->container['project_information'] = isset($data['project_information']) ? $data['project_information'] : null;
        $this->container['exchange_phase'] = isset($data['exchange_phase']) ? $data['exchange_phase'] : null;
        $this->container['origin'] = isset($data['origin']) ? $data['origin'] : null;
        $this->container['creation_date'] = isset($data['creation_date']) ? $data['creation_date'] : null;
        $this->container['offer_by_date'] = isset($data['offer_by_date']) ? $data['offer_by_date'] : null;
        $this->container['decision_date'] = isset($data['decision_date']) ? $data['decision_date'] : null;
        $this->container['submission_location'] = isset($data['submission_location']) ? $data['submission_location'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['price_information'] = isset($data['price_information']) ? $data['price_information'] : null;
        $this->container['project_catalogues'] = isset($data['project_catalogues']) ? $data['project_catalogues'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['project_hourly_wage'] === null) {
            $invalidProperties[] = "'project_hourly_wage' can't be null";
        }
        if ($this->container['project_tax_rate'] === null) {
            $invalidProperties[] = "'project_tax_rate' can't be null";
        }
        if ($this->container['contains_duplicate_item_numbers'] === null) {
            $invalidProperties[] = "'contains_duplicate_item_numbers' can't be null";
        }
        if ($this->container['ignore_duplicate_item_numbers'] === null) {
            $invalidProperties[] = "'ignore_duplicate_item_numbers' can't be null";
        }
        if ($this->container['ignore_child_price_updates'] === null) {
            $invalidProperties[] = "'ignore_child_price_updates' can't be null";
        }
        if ($this->container['deducted_price'] === null) {
            $invalidProperties[] = "'deducted_price' can't be null";
        }
        if ($this->container['deduction_factor'] === null) {
            $invalidProperties[] = "'deduction_factor' can't be null";
        }
        if ($this->container['total_price'] === null) {
            $invalidProperties[] = "'total_price' can't be null";
        }
        if ($this->container['total_price_gross'] === null) {
            $invalidProperties[] = "'total_price_gross' can't be null";
        }
        if ($this->container['total_price_gross_deducted'] === null) {
            $invalidProperties[] = "'total_price_gross_deducted' can't be null";
        }
        if ($this->container['price_type'] === null) {
            $invalidProperties[] = "'price_type' can't be null";
        }
        if ($this->container['exchange_phase'] === null) {
            $invalidProperties[] = "'exchange_phase' can't be null";
        }
        if ($this->container['origin'] === null) {
            $invalidProperties[] = "'origin' can't be null";
        }
        if ($this->container['creation_date'] === null) {
            $invalidProperties[] = "'creation_date' can't be null";
        }
        if ($this->container['offer_by_date'] === null) {
            $invalidProperties[] = "'offer_by_date' can't be null";
        }
        if ($this->container['decision_date'] === null) {
            $invalidProperties[] = "'decision_date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets project_hourly_wage
     *
     * @return float
     */
    public function getProjectHourlyWage()
    {
        return $this->container['project_hourly_wage'];
    }

    /**
     * Sets project_hourly_wage
     *
     * @param float $project_hourly_wage project_hourly_wage
     *
     * @return $this
     */
    public function setProjectHourlyWage($project_hourly_wage)
    {
        $this->container['project_hourly_wage'] = $project_hourly_wage;

        return $this;
    }

    /**
     * Gets project_tax_rate
     *
     * @return float
     */
    public function getProjectTaxRate()
    {
        return $this->container['project_tax_rate'];
    }

    /**
     * Sets project_tax_rate
     *
     * @param float $project_tax_rate project_tax_rate
     *
     * @return $this
     */
    public function setProjectTaxRate($project_tax_rate)
    {
        $this->container['project_tax_rate'] = $project_tax_rate;

        return $this;
    }

    /**
     * Gets project_price_components
     *
     * @return string[]
     */
    public function getProjectPriceComponents()
    {
        return $this->container['project_price_components'];
    }

    /**
     * Sets project_price_components
     *
     * @param string[] $project_price_components project_price_components
     *
     * @return $this
     */
    public function setProjectPriceComponents($project_price_components)
    {
        $this->container['project_price_components'] = $project_price_components;

        return $this;
    }

    /**
     * Gets project_item_number_schema
     *
     * @return \Swagger\Client\Model\ItemNumberSchemaDto
     */
    public function getProjectItemNumberSchema()
    {
        return $this->container['project_item_number_schema'];
    }

    /**
     * Sets project_item_number_schema
     *
     * @param \Swagger\Client\Model\ItemNumberSchemaDto $project_item_number_schema project_item_number_schema
     *
     * @return $this
     */
    public function setProjectItemNumberSchema($project_item_number_schema)
    {
        $this->container['project_item_number_schema'] = $project_item_number_schema;

        return $this;
    }

    /**
     * Gets elements
     *
     * @return \Swagger\Client\Model\IElementDto[]
     */
    public function getElements()
    {
        return $this->container['elements'];
    }

    /**
     * Sets elements
     *
     * @param \Swagger\Client\Model\IElementDto[] $elements elements
     *
     * @return $this
     */
    public function setElements($elements)
    {
        $this->container['elements'] = $elements;

        return $this;
    }

    /**
     * Gets project_labour_time_label
     *
     * @return string
     */
    public function getProjectLabourTimeLabel()
    {
        return $this->container['project_labour_time_label'];
    }

    /**
     * Sets project_labour_time_label
     *
     * @param string $project_labour_time_label project_labour_time_label
     *
     * @return $this
     */
    public function setProjectLabourTimeLabel($project_labour_time_label)
    {
        $this->container['project_labour_time_label'] = $project_labour_time_label;

        return $this;
    }

    /**
     * Gets contains_duplicate_item_numbers
     *
     * @return bool
     */
    public function getContainsDuplicateItemNumbers()
    {
        return $this->container['contains_duplicate_item_numbers'];
    }

    /**
     * Sets contains_duplicate_item_numbers
     *
     * @param bool $contains_duplicate_item_numbers contains_duplicate_item_numbers
     *
     * @return $this
     */
    public function setContainsDuplicateItemNumbers($contains_duplicate_item_numbers)
    {
        $this->container['contains_duplicate_item_numbers'] = $contains_duplicate_item_numbers;

        return $this;
    }

    /**
     * Gets ignore_duplicate_item_numbers
     *
     * @return bool
     */
    public function getIgnoreDuplicateItemNumbers()
    {
        return $this->container['ignore_duplicate_item_numbers'];
    }

    /**
     * Sets ignore_duplicate_item_numbers
     *
     * @param bool $ignore_duplicate_item_numbers ignore_duplicate_item_numbers
     *
     * @return $this
     */
    public function setIgnoreDuplicateItemNumbers($ignore_duplicate_item_numbers)
    {
        $this->container['ignore_duplicate_item_numbers'] = $ignore_duplicate_item_numbers;

        return $this;
    }

    /**
     * Gets total_price_gross_by_tax_rate
     *
     * @return \Swagger\Client\Model\GrossPriceComponentDto[]
     */
    public function getTotalPriceGrossByTaxRate()
    {
        return $this->container['total_price_gross_by_tax_rate'];
    }

    /**
     * Sets total_price_gross_by_tax_rate
     *
     * @param \Swagger\Client\Model\GrossPriceComponentDto[] $total_price_gross_by_tax_rate total_price_gross_by_tax_rate
     *
     * @return $this
     */
    public function setTotalPriceGrossByTaxRate($total_price_gross_by_tax_rate)
    {
        $this->container['total_price_gross_by_tax_rate'] = $total_price_gross_by_tax_rate;

        return $this;
    }

    /**
     * Gets ignore_child_price_updates
     *
     * @return bool
     */
    public function getIgnoreChildPriceUpdates()
    {
        return $this->container['ignore_child_price_updates'];
    }

    /**
     * Sets ignore_child_price_updates
     *
     * @param bool $ignore_child_price_updates ignore_child_price_updates
     *
     * @return $this
     */
    public function setIgnoreChildPriceUpdates($ignore_child_price_updates)
    {
        $this->container['ignore_child_price_updates'] = $ignore_child_price_updates;

        return $this;
    }

    /**
     * Gets deducted_price
     *
     * @return float
     */
    public function getDeductedPrice()
    {
        return $this->container['deducted_price'];
    }

    /**
     * Sets deducted_price
     *
     * @param float $deducted_price deducted_price
     *
     * @return $this
     */
    public function setDeductedPrice($deducted_price)
    {
        $this->container['deducted_price'] = $deducted_price;

        return $this;
    }

    /**
     * Gets deduction_factor
     *
     * @return float
     */
    public function getDeductionFactor()
    {
        return $this->container['deduction_factor'];
    }

    /**
     * Sets deduction_factor
     *
     * @param float $deduction_factor deduction_factor
     *
     * @return $this
     */
    public function setDeductionFactor($deduction_factor)
    {
        $this->container['deduction_factor'] = $deduction_factor;

        return $this;
    }

    /**
     * Gets total_price
     *
     * @return float
     */
    public function getTotalPrice()
    {
        return $this->container['total_price'];
    }

    /**
     * Sets total_price
     *
     * @param float $total_price total_price
     *
     * @return $this
     */
    public function setTotalPrice($total_price)
    {
        $this->container['total_price'] = $total_price;

        return $this;
    }

    /**
     * Gets total_price_gross
     *
     * @return float
     */
    public function getTotalPriceGross()
    {
        return $this->container['total_price_gross'];
    }

    /**
     * Sets total_price_gross
     *
     * @param float $total_price_gross total_price_gross
     *
     * @return $this
     */
    public function setTotalPriceGross($total_price_gross)
    {
        $this->container['total_price_gross'] = $total_price_gross;

        return $this;
    }

    /**
     * Gets total_price_gross_deducted
     *
     * @return float
     */
    public function getTotalPriceGrossDeducted()
    {
        return $this->container['total_price_gross_deducted'];
    }

    /**
     * Sets total_price_gross_deducted
     *
     * @param float $total_price_gross_deducted total_price_gross_deducted
     *
     * @return $this
     */
    public function setTotalPriceGrossDeducted($total_price_gross_deducted)
    {
        $this->container['total_price_gross_deducted'] = $total_price_gross_deducted;

        return $this;
    }

    /**
     * Gets price_type
     *
     * @return \Swagger\Client\Model\PriceTypeDto
     */
    public function getPriceType()
    {
        return $this->container['price_type'];
    }

    /**
     * Sets price_type
     *
     * @param \Swagger\Client\Model\PriceTypeDto $price_type price_type
     *
     * @return $this
     */
    public function setPriceType($price_type)
    {
        $this->container['price_type'] = $price_type;

        return $this;
    }

    /**
     * Gets bidder
     *
     * @return \Swagger\Client\Model\PartyInformationDto
     */
    public function getBidder()
    {
        return $this->container['bidder'];
    }

    /**
     * Sets bidder
     *
     * @param \Swagger\Client\Model\PartyInformationDto $bidder bidder
     *
     * @return $this
     */
    public function setBidder($bidder)
    {
        $this->container['bidder'] = $bidder;

        return $this;
    }

    /**
     * Gets gaeb_xml_id
     *
     * @return string
     */
    public function getGaebXmlId()
    {
        return $this->container['gaeb_xml_id'];
    }

    /**
     * Sets gaeb_xml_id
     *
     * @param string $gaeb_xml_id gaeb_xml_id
     *
     * @return $this
     */
    public function setGaebXmlId($gaeb_xml_id)
    {
        $this->container['gaeb_xml_id'] = $gaeb_xml_id;

        return $this;
    }

    /**
     * Gets project_information
     *
     * @return object
     */
    public function getProjectInformation()
    {
        return $this->container['project_information'];
    }

    /**
     * Sets project_information
     *
     * @param object $project_information project_information
     *
     * @return $this
     */
    public function setProjectInformation($project_information)
    {
        $this->container['project_information'] = $project_information;

        return $this;
    }

    /**
     * Gets exchange_phase
     *
     * @return \Swagger\Client\Model\ExchangePhaseDto
     */
    public function getExchangePhase()
    {
        return $this->container['exchange_phase'];
    }

    /**
     * Sets exchange_phase
     *
     * @param \Swagger\Client\Model\ExchangePhaseDto $exchange_phase exchange_phase
     *
     * @return $this
     */
    public function setExchangePhase($exchange_phase)
    {
        $this->container['exchange_phase'] = $exchange_phase;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return \Swagger\Client\Model\OriginDto
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param \Swagger\Client\Model\OriginDto $origin origin
     *
     * @return $this
     */
    public function setOrigin($origin)
    {
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param \DateTime $creation_date creation_date
     *
     * @return $this
     */
    public function setCreationDate($creation_date)
    {
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets offer_by_date
     *
     * @return \DateTime
     */
    public function getOfferByDate()
    {
        return $this->container['offer_by_date'];
    }

    /**
     * Sets offer_by_date
     *
     * @param \DateTime $offer_by_date offer_by_date
     *
     * @return $this
     */
    public function setOfferByDate($offer_by_date)
    {
        $this->container['offer_by_date'] = $offer_by_date;

        return $this;
    }

    /**
     * Gets decision_date
     *
     * @return \DateTime
     */
    public function getDecisionDate()
    {
        return $this->container['decision_date'];
    }

    /**
     * Sets decision_date
     *
     * @param \DateTime $decision_date decision_date
     *
     * @return $this
     */
    public function setDecisionDate($decision_date)
    {
        $this->container['decision_date'] = $decision_date;

        return $this;
    }

    /**
     * Gets submission_location
     *
     * @return string
     */
    public function getSubmissionLocation()
    {
        return $this->container['submission_location'];
    }

    /**
     * Sets submission_location
     *
     * @param string $submission_location submission_location
     *
     * @return $this
     */
    public function setSubmissionLocation($submission_location)
    {
        $this->container['submission_location'] = $submission_location;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets price_information
     *
     * @return \Swagger\Client\Model\PriceInformationDto
     */
    public function getPriceInformation()
    {
        return $this->container['price_information'];
    }

    /**
     * Sets price_information
     *
     * @param \Swagger\Client\Model\PriceInformationDto $price_information price_information
     *
     * @return $this
     */
    public function setPriceInformation($price_information)
    {
        $this->container['price_information'] = $price_information;

        return $this;
    }

    /**
     * Gets project_catalogues
     *
     * @return \Swagger\Client\Model\CatalogueDto[]
     */
    public function getProjectCatalogues()
    {
        return $this->container['project_catalogues'];
    }

    /**
     * Sets project_catalogues
     *
     * @param \Swagger\Client\Model\CatalogueDto[] $project_catalogues project_catalogues
     *
     * @return $this
     */
    public function setProjectCatalogues($project_catalogues)
    {
        $this->container['project_catalogues'] = $project_catalogues;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


